import nltk


from textblob import TextBlob

blob1 = TextBlob("Team members are over-worked and not collaborating properly. ")
print(format(blob1.sentiment))
blob1 = TextBlob("At this current rate, we may not deliver on all the KPIs. ")
print(format(blob1.sentiment))
blob1 = TextBlob("My ideas are not always considered. ")
print(format(blob1.sentiment))
blob1 = TextBlob("I am more involved then required due to an unequal distribution of roles and responsibilities, or team contribution. ")
print(format(blob1.sentiment))
blob1 = TextBlob("I don't have a clear understanding off other team members roles or responsibilities. I feel like other people may not have a clear understanding either.")
print(format(blob1.sentiment))
blob1 = TextBlob("I don't think the research being conducted is in-depth enough to confidently complete the project. Mistakes might be made. ")
print(format(blob1.sentiment))
blob1 = TextBlob("There needs to be greater transparency. The whole team needs to be able to see each individuals contribution. This will reduce re-work and ensure individuals are kept accountable.  ")
print(format(blob1.sentiment))
blob1 = TextBlob("The correct decisions are made 50 of the time. This leads to multiple issues arising, time is allocated to fixing issues instead of the objectives of the project. ")
print(format(blob1.sentiment))
blob1 = TextBlob("In small ways. Major decisions are made by more senior staff members. ")
print(format(blob1.sentiment))
blob1 = TextBlob("The company structure limits this. ")
print(format(blob1.sentiment))
blob1 = TextBlob("The management team need to approve each decision. This adds unnecessary time to the project.  ")
print(format(blob1.sentiment))
blob1 = TextBlob("Could be improved. ")
print(format(blob1.sentiment))
blob1 = TextBlob("All the team members differ in seniority, this leads to issues when it comes to influence. ")
print(format(blob1.sentiment))
blob1 = TextBlob("Similar projects required 5 months, we have only been assigned 3 months; and less staff members. ")
print(format(blob1.sentiment))
blob1 = TextBlob("The likely hood we will complete the objectives is high; not with the budget and time allocated at current. ")
print(format(blob1.sentiment))
blob1 = TextBlob("The budget we have been assigned is $20,000 and comparative projects required $30,000. ")
print(format(blob1.sentiment))
blob1 = TextBlob("The staff of 8 are overworked. We should have 12. A few staff members are not contributing enough leading to me personally having too much of the workload. ")
print(format(blob1.sentiment))
blob1 = TextBlob("The majority of staff members are solving problems collaboratively. Some senior staff are blaming lower level'd staff. ")
print(format(blob1.sentiment))

blob1 = TextBlob("The management team could improve their responsiveness. ")
print(format(blob1.sentiment))
blob2 = TextBlob("If anything, the staff are over-experienced. ")
print(format(blob2.sentiment))
blob3 = TextBlob("The company culture is such that projects are completed in a set manor. ")
print(format(blob3.sentiment))
blob4 = TextBlob("Not enough resources. Not enough time. Not enough budget. ")
print(format(blob4.sentiment))
blob5 = TextBlob("An unpopular opinion might affect a staff members prospects for promotion. ")
print(format(blob5.sentiment))
blob6 = TextBlob("All decisions must be cleared with the management team, which is time wasting. ")
print(format(blob6.sentiment))
blob7 = TextBlob("The team is working well together, but I feel that we could be progressing the schedule faster.")
print(format(blob7.sentiment))
blob8 = TextBlob("We need to collaborate more effectively to speed progress up.")
print(format(blob8.sentiment))
blob9 = TextBlob("I am confident we will deliver a successful and high quality project, however I am concerned that we are going to meet the deadline. ")
print(format(blob9.sentiment))
blob10 = TextBlob("I am very proud working on this world first initative.")
print(format(blob10.sentiment))
blob11 = TextBlob("I think the schedule pressures will become more apparent and that we need to consider additional resources and the cost implications of that. ")
print(format(blob11.sentiment))
blob12 = TextBlob("Minor cost over-runs to accommodate additional resources that weren't factored in to the project during the planning stage.")
print(format(blob12.sentiment))
blob13 = TextBlob("I would rate this higher if I had regular feedback from my leaders to affirm their trust in me.")
print(format(blob13.sentiment))
blob14 = TextBlob("The present workforce is overly very mobile, widely distributed across the globe, and often desk-lessworking remotely. The majority of the respondents team are feeling reported being frustrated by the tools and platforms available to talk to their other team-mates.")
print(format(blob14.sentiment))
blob15 = TextBlob("Passionate")
print(format(blob15.sentiment))
blob16 = TextBlob("There is not an equal contribution from all staff members. Staff are using their seniority as an excuse to not contribute.")
print(format(blob16.sentiment))
blob17 = TextBlob("There are several issues that need to be addressed for this project to be completed. At this current rate it will not be completed on-time or on-budget. ")
print(format(blob17.sentiment))
blob18 = TextBlob("The present workforce is overly very mobile, widely distributed across the globe, and often desk-lessworking remotely. The majority of the respondents team are feeling reported being frustrated by the tools and platforms available to talk to their other team-mates.")
print(format(blob18.sentiment))
blob19 = TextBlob("Manager didn't provide enough information; on changes in strategy at the workplace, employees couldn't deliver as expected of them.")
print(format(blob19.sentiment))
blob20 = TextBlob("I have a clear definition of the project and the purpose of the project is clear and that everyone understands how the deliverables and benefits will be measured. I have a common understanding with the client about what is in and out of scope.")
print(format(blob20.sentiment))
blob21 = TextBlob("The schedule pressures aren't being openly discussed. The next milestone is only 2 weeks away and we need another 5 people on site to hit that target. I think the client is trying to avoid a commercial discussion as they may be concerned about the additional cost to the project. ")
print(format(blob21.sentiment))
blob21 = TextBlob("I feel that the project is going to be successful but our schedule performance could be improved by adding and mobilising additional resources to site to speed up the construction. The project should consider additional resources.")
print(format(blob21.sentiment))
blob21 = TextBlob("We are doing a terrible job of communicating the list of activities which is causing delays")
print(format(blob21.sentiment))
blob21 = TextBlob("Also departments or team members didn't share information, goals, priorities, and processes among themselves.")
print(format(blob21.sentiment))
blob21 = TextBlob("good")
print(format(blob21.sentiment))
blob21 = TextBlob("How bad the coffee is.")
print(format(blob21.sentiment))
blob21 = TextBlob("I have a clear definition of the project and the purpose of the project is clear and that everyone understands how the deliverables and benefits will be measured. I have a common understanding with the client about what is in and out of scope.")
print(format(blob21.sentiment))
blob21 = TextBlob("It's awesome")
print(format(blob21.sentiment))
blob21 = TextBlob("We are unwilling to ask for help when needed and We do not communicate with other employees.")
print(format(blob21.sentiment))

blob21 = TextBlob("I don't think Mike is spending enough time on this project at the moment, where he should be entirely focused on it. It might risk the overall schedule. ")
print(format(blob21.sentiment))
blob21 = TextBlob("I am not confident that a particular requirement is achievable given the constraint of existing technology.")
print(format(blob21.sentiment))


