version: '2'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn --bind 0.0.0.0:8000 mysite.wsgi:application
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./mysite/.env.prod
    depends_on:
      - db
  db:
    image: postgres:9.5.23-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # environment:
    #   - POSTGRES_USER=fullstack412
    #   - POSTGRES_PASSWORD=piggy41294
    #   - POSTGRES_DB=pulse
    env_file:
      - ./mysite/.env.prod.db

volumes:
  postgres_data:
  static_volume:
