version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn projectai_puse_cms.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:9.5.23-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fullstack412
      - POSTGRES_PASSWORD=piggy41294
      - POSTGRES_DB=pulse

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web