# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-07-16 01:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_auto_20200408_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuideMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField(default=True, verbose_name='Guide Mode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guidemode', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
