# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Project'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='shGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shgroup.SHGroup'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.Team'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='userPermission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Permission'),
        ),
    ]
