# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-02 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_project_client'),
        ('team', '0002_auto_20200120_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='organization',
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.Project'),
            preserve_default=False,
        ),
    ]
