# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20200401_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Project'),
        ),
    ]
