# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-03 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.CharField(max_length=50)),
                ('pageLink', models.URLField(max_length=255)),
            ],
        ),
    ]
