# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-09 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import rgbfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='color',
            field=rgbfield.fields.RGBColorField(default='#afd8f8'),
        ),
        migrations.AddField(
            model_name='journey',
            name='orderId',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey',
            name='xPos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey',
            name='yPos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
