# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-06-04 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20200828_0149'),
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
            preserve_default=False,
        ),
    ]
