# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-09 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageNav',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='page_order', serialize=False, to='cms.Page')),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
