# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-09 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import page_setting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_extra_field', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PageSetting',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='pages', serialize=False, to='cms.Page')),
                ('pageType', enumfields.fields.EnumField(enum=page_setting.models.PageType, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='extendedpage',
            name='page',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='extended_fields', to='cms.Page', verbose_name='Page'),
        ),
    ]
