# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 17:38
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_setting', '0005_auto_20191029_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesetting',
            name='page',
            field=cms.models.fields.PageField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='pages', serialize=False, to='cms.Page', unique=True),
        ),
    ]
