# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptclass',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptinstance',
            name='preferLabel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
