# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-03-02 07:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import shgroup.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyThemeUpDownVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyTheme', models.TextField(default='')),
                ('tab', models.PositiveIntegerField(default=0)),
                ('voteValue', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyMapLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMapLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectUserTitle', models.CharField(blank=True, help_text='Role / Title of the stakeholder on this Project', max_length=50, verbose_name='Project Title')),
                ('projectUserRoleDesc', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('isSuperUser', models.BooleanField(default=False, verbose_name='Reveal Dashboards')),
                ('projectOrganization', models.CharField(blank=True, default='', max_length=200, verbose_name='Project Organization')),
                ('isCGroup1', models.BooleanField(default=False)),
                ('isCGroup2', models.BooleanField(default=False)),
                ('isCGroup3', models.BooleanField(default=False)),
                ('sendInvite', models.BooleanField(default=False)),
                ('sendEmail', models.BooleanField(default=False)),
                ('projectAdmin', models.NullBooleanField(default=None, verbose_name='Project Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isArchived', models.BooleanField(default=False)),
                ('addByProjectUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shgroup.ProjectUser', verbose_name='Added By')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shgroups', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('teams', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('organizations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SHCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHCategoryName', models.CharField(blank=True, max_length=50)),
                ('SHCategoryDesc', models.CharField(blank=True, max_length=200)),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('icon', models.FileField(blank=True, upload_to='uploads/shcategory')),
                ('mapType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shgroup.MapType')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SHGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHGroupName', models.CharField(max_length=255)),
                ('SHGroupAbbrev', models.CharField(blank=True, max_length=50)),
                ('responsePercent', shgroup.models.InegerPercentageField(default=0, verbose_name='Throttle % Response')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SHMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationshipStatus', models.CharField(blank=True, max_length=100)),
                ('projectUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectUser', to='shgroup.ProjectUser')),
                ('shCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shgroup.SHCategory')),
                ('subProjectUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subProjectUser', to='shgroup.ProjectUser')),
            ],
        ),
        migrations.CreateModel(
            name='SHType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shTypeName', models.CharField(blank=True, max_length=50)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='projectuser',
            name='shGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shgroup.SHGroup', verbose_name='SHGroup'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='shType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shgroup.SHType', verbose_name='SHType'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='Project Team'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmaplayout',
            name='projectUser',
            field=models.ManyToManyField(blank=True, to='shgroup.ProjectUser'),
        ),
        migrations.AddField(
            model_name='projectmaplayout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mymaplayout',
            name='projectUser',
            field=models.ManyToManyField(blank=True, to='shgroup.ProjectUser'),
        ),
        migrations.AddField(
            model_name='mymaplayout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keythemeupdownvote',
            name='projectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shgroup.ProjectUser'),
        ),
        migrations.AddField(
            model_name='keythemeupdownvote',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AlterUniqueTogether(
            name='shmapping',
            unique_together=set([('shCategory', 'projectUser', 'subProjectUser')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together=set([('survey', 'user')]),
        ),
    ]
