# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shcategory',
            name='shGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shgroup.SHGroup'),
        ),
        migrations.AlterField(
            model_name='shcategory',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='shgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Project'),
        ),
        migrations.AlterField(
            model_name='shgroupuser',
            name='shGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shgroup.SHGroup'),
        ),
        migrations.AlterField(
            model_name='shgroupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shmapping',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='shmapping',
            name='shCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shgroup.SHCategory'),
        ),
        migrations.AlterField(
            model_name='shmapping',
            name='subjectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjectUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
