# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='userPermission',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission'),
        ),
    ]
