# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-18 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0002_auto_20200117_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymaplayout',
            name='projectUser',
        ),
        migrations.AddField(
            model_name='mymaplayout',
            name='projectUser',
            field=models.ManyToManyField(blank=True, to='shgroup.ProjectUser'),
        ),
        migrations.RemoveField(
            model_name='projectmaplayout',
            name='projectUser',
        ),
        migrations.AddField(
            model_name='projectmaplayout',
            name='projectUser',
            field=models.ManyToManyField(blank=True, to='shgroup.ProjectUser'),
        ),
    ]
