# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0002_auto_20191029_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shcategory',
            name='SHCategoryDesc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shgroup',
            name='SHGroupAbbrev',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
