# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0002_auto_20191101_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.Team'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='userPermission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Permission'),
        ),
    ]
