# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-21 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0003_auto_20200118_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='shGroup',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='shCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shgroup.SHCategory'),
            preserve_default=False,
        ),
    ]
