# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0003_auto_20191101_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='shgroupuser',
            name='projectUser',
        ),
        migrations.RemoveField(
            model_name='shgroupuser',
            name='shGroup',
        ),
        migrations.RemoveField(
            model_name='shmapping',
            name='user',
        ),
        migrations.AddField(
            model_name='shmapping',
            name='projectUser',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='shgroup.ProjectUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shcategory',
            name='mapType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shgroup.MapType'),
        ),
        migrations.DeleteModel(
            name='SHGroupUser',
        ),
    ]
