# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-27 01:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200120_1201'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_remove_project_client'),
        ('shgroup', '0004_auto_20200121_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='shCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shgroup.SHCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together=set([('project', 'user', 'team')]),
        ),
    ]
