# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-27 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0005_auto_20200126_1743'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mymaplayout',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='projectmaplayout',
            unique_together=set([]),
        ),
    ]
