# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-09 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0006_auto_20200127_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
