# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-09 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0007_auto_20200309_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shcategory',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/shcategory'),
        ),
    ]
