# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-18 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0009_auto_20200310_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='userPermission',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='projectUserTitle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
