# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0010_auto_20200318_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='projectUserRoleDesc',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
