# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-07 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_project_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shgroup', '0011_projectuser_projectuserroledesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='projectUserRoleDesc',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='projectUserTitle',
            field=models.CharField(blank=True, max_length=50, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='Team'),
        ),
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together=set([('project', 'user')]),
        ),
    ]
