# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-13 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0012_auto_20200406_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='shCategory',
        ),
        migrations.RemoveField(
            model_name='shcategory',
            name='shGroup',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='shGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shgroup.SHGroup', verbose_name='SHGroup'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='Project Team'),
        ),
    ]
