# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-13 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0015_remove_shgroup_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shmapping',
            unique_together=set([('shCategory', 'projectUser')]),
        ),
    ]
