# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-14 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_projectvideoupload'),
        ('shgroup', '0016_auto_20200413_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='shgroup',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.Project'),
            preserve_default=False,
        ),
    ]
