# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-16 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0017_shgroup_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='projectUserRoleDesc',
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='projectUserTitle',
            field=models.CharField(blank=True, help_text='Role / Title of the stakeholder on this Project', max_length=50, verbose_name='Project Title'),
        ),
    ]
