# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-21 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20200520_2015'),
        ('shgroup', '0018_auto_20200416_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shgroup',
            name='project',
        ),
        migrations.AddField(
            model_name='shgroup',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.Survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shmapping',
            name='subProjectUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subProjectUser', to='shgroup.ProjectUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shmapping',
            name='projectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projectUser', to='shgroup.ProjectUser'),
        ),
        migrations.AlterUniqueTogether(
            name='shmapping',
            unique_together=set([('shCategory', 'projectUser', 'subProjectUser')]),
        ),
    ]
