# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-29 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20200528_1744'),
        ('shgroup', '0020_auto_20200527_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.Project'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='survey',
        ),
    ]
