# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-29 01:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20200528_1744'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shgroup', '0021_auto_20200528_1824'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together=set([('project', 'user')]),
        ),
    ]
