# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-29 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0022_auto_20200528_1825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together=set([]),
        ),
    ]
