# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-29 03:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0009_auto_20200528_1744'),
        ('shgroup', '0023_auto_20200528_2021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together=set([('project', 'user')]),
        ),
    ]
