# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-04 01:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0010_auto_20200603_1855'),
        ('shgroup', '0024_auto_20200528_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.Survey'),
            preserve_default=False,
        ),
        #migrations.RemoveField(
        #    model_name='projectuser',
        #    name='project',
        #),
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together=set([('survey', 'user')]),
        ),
    ]
