# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-04 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0025_auto_20200603_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='project',
        ),
    ]
