# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-08-28 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0028_auto_20200617_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='isCGroup1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='isCGroup2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='isCGroup3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='isTeamMember',
            field=models.BooleanField(default=False),
        ),
    ]
