# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-09-30 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0029_auto_20200828_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='sendInvite',
            field=models.BooleanField(default=False),
        ),
    ]
