# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-03-10 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0030_projectuser_sendinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyThemeUpDownVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyTheme', models.TextField(default='')),
                ('voteValue', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projectUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shgroup.ProjectUser')),
            ],
        ),
    ]
