# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-03-25 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20200828_0149'),
        ('shgroup', '0031_keythemeupdownvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='keythemeupdownvote',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keythemeupdownvote',
            name='tab',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
