# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-05-19 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0032_auto_20210325_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='isSuperUser',
            field=models.BooleanField(default=False),
        ),
    ]
