# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-05-19 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0033_projectuser_issuperuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='shgroup',
            name='responsePercent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
