# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-05-25 03:25
from __future__ import unicode_literals

from django.db import migrations
import shgroup.models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0035_auto_20210521_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shgroup',
            name='responsePercent',
            field=shgroup.models.InegerPercentageField(default=0, verbose_name='Throttle % Response'),
        ),
    ]
