# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-06-22 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0037_projectuser_projectorganization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='isTeamMember',
        ),
    ]
