# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-06-22 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0038_remove_projectuser_isteammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='shType',
            field=models.CharField(choices=[(0, 'Team Member'), (1, 'Stakeholder')], default=0, max_length=1),
        ),
    ]
