# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-08-31 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0040_auto_20210622_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='sendEmail',
            field=models.BooleanField(default=False),
        ),
    ]
