# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-10-22 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0042_auto_20211021_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='addByProjectUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shgroup.ProjectUser', verbose_name='Added By'),
        ),
    ]
