# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-11-01 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0043_projectuser_addbyprojectuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='projectUserRoleDesc',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
    ]
