# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-11-19 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0044_projectuser_projectuserroledesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
    ]
