# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-03-07 06:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_auto_20211103_1444'),
        ('shgroup', '0045_projectuser_isarchived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shgroups', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('teams', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('organizations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
    ]
