# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-04-27 16:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0046_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='keythemeupdownvote',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
