# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Client'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Project'),
        ),
    ]
