# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-08 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_project_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVideoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('videoFile', models.FileField(upload_to='uploads/pvideo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Project')),
            ],
        ),
    ]
