# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-01 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_projectvideoupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['driveOrder']},
        ),
        migrations.AddField(
            model_name='driver',
            name='driveOrder',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
