# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-19 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200430_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabName', models.CharField(max_length=40)),
                ('pageName', models.CharField(max_length=200)),
                ('pageContent', tinymce.models.HTMLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Project')),
            ],
        ),
    ]
