# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-21 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='ConfigPage',
        ),
        migrations.AddField(
            model_name='driver',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.Survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.Client'),
            preserve_default=False,
        ),
    ]
