# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-25 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rgbfield.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20200520_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='NikelMobilePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.CharField(max_length=50)),
                ('pageText', models.CharField(max_length=500)),
                ('backgroundColor', rgbfield.fields.RGBColorField(default='#afd8f8')),
                ('pageContent', tinymce.models.HTMLField()),
                ('pageOrder', models.PositiveIntegerField(default=0, verbose_name='Page Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Project')),
            ],
            options={
                'ordering': ['pageOrder'],
            },
        ),
    ]
