# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-29 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import rgbfield.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20200525_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nikelmobilepage',
            name='backgroundColor',
            field=rgbfield.fields.RGBColorField(default='#afd8f8'),
        ),
        migrations.AlterField(
            model_name='nikelmobilepage',
            name='pageContent',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='nikelmobilepage',
            name='pageText',
            field=models.CharField(max_length=500),
        ),
    ]
