# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-04 01:55
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20200528_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nikelmobilepage',
            name='backgroundColor',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='nikelmobilepage',
            name='pageText',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
