# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-04 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20200603_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configpage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='nikelmobilepage',
            name='project',
        ),
        migrations.AddField(
            model_name='configpage',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.Survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nikelmobilepage',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.Survey'),
            preserve_default=False,
        ),
    ]
