# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-11 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20200610_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='isStandard',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
