# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-11 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_survey_isstandard'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooltipguide',
            name='place',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
