# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-11 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_tooltipguide_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='isStandard',
            field=models.BooleanField(default=False),
        ),
    ]
