# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-12 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20200612_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tooltipguide',
            options={'ordering': ['tooltipOrder']},
        ),
        migrations.AddField(
            model_name='tooltipguide',
            name='tooltipOrder',
            field=models.PositiveIntegerField(default=0, verbose_name='Tooltip Order'),
        ),
    ]
