# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-29 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20200617_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
