# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-07-22 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_survey_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='isStandard',
            field=models.BooleanField(default=False),
        ),
    ]
