# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-08-28 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_driver_isstandard'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='customGroup1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='customGroup2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='customGroup3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
