# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-07-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20200828_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='anonymityThreshold',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
