# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-10-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_survey_seatspurchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='projectManager',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
