# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-11-03 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_auto_20211029_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='companyLogo',
            field=models.ImageField(blank=True, upload_to='uploads/logo', verbose_name='Company Logo'),
        ),
        migrations.AddField(
            model_name='survey',
            name='projectCode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='projectLogo',
            field=models.ImageField(blank=True, upload_to='uploads/logo', verbose_name='Project Logo'),
        ),
    ]
