# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-04-13 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_auto_20211103_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='puchasePrice',
            field=models.FloatField(default=14.99),
        ),
    ]
