# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-09 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdriver', models.CharField(blank=True, max_length=50)),
                ('questionText', models.CharField(max_length=1000)),
                ('questionSequence', models.PositiveIntegerField(default=5)),
                ('sliderTextLeft', models.CharField(blank=True, max_length=50)),
                ('sliderTextRight', models.CharField(blank=True, max_length=50)),
                ('skipOptionYN', models.BooleanField(default=True)),
                ('skipResponses', models.CharField(blank=True, max_length=1000)),
                ('topicPrompt', models.CharField(blank=True, max_length=255)),
                ('commentPrompt', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AMQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AMQuestionSHGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AMResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integerValue', models.PositiveIntegerField(blank=True)),
                ('topicValue', models.TextField(blank=True)),
                ('commentValue', models.TextField(blank=True)),
                ('skipValue', models.TextField(blank=True)),
                ('topicTags', models.TextField(blank=True)),
                ('commentTags', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AMResponseTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PageAMQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amQuestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutme.AMQuestion')),
            ],
        ),
    ]
