# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-03-02 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
        ('shgroup', '0001_initial'),
        ('setting', '0001_initial'),
        ('aboutme', '0001_initial'),
        ('option', '0001_initial'),
        ('page_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageamquestion',
            name='pageSetting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ampagesetting', to='page_setting.PageSetting'),
        ),
        migrations.AddField(
            model_name='amresponsetopic',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMQuestion'),
        ),
        migrations.AddField(
            model_name='amresponsetopic',
            name='responseUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shgroup.ProjectUser'),
        ),
        migrations.AddField(
            model_name='amresponseacknowledgement',
            name='amResponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMResponse'),
        ),
        migrations.AddField(
            model_name='amresponseacknowledgement',
            name='projectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amCommentProjectUser', to='shgroup.ProjectUser'),
        ),
        migrations.AddField(
            model_name='amresponse',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMQuestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='amresponse',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Project'),
        ),
        migrations.AddField(
            model_name='amresponse',
            name='projectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amProjectUser', to='shgroup.ProjectUser'),
        ),
        migrations.AddField(
            model_name='amresponse',
            name='subProjectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amSubProjectUser', to='shgroup.ProjectUser'),
        ),
        migrations.AddField(
            model_name='amresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='amquestionskipoption',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMQuestion'),
        ),
        migrations.AddField(
            model_name='amquestionskipoption',
            name='skipOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.SkipOption'),
        ),
        migrations.AddField(
            model_name='amquestionshgroup',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMQuestion'),
        ),
        migrations.AddField(
            model_name='amquestionshgroup',
            name='shGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shgroup.SHGroup'),
        ),
        migrations.AddField(
            model_name='amquestionoption',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMQuestion'),
        ),
        migrations.AddField(
            model_name='amquestionoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option'),
        ),
        migrations.AddField(
            model_name='amquestion',
            name='controlType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.ControlType'),
        ),
        migrations.AddField(
            model_name='amquestion',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Driver'),
        ),
        migrations.AddField(
            model_name='amquestion',
            name='option',
            field=models.ManyToManyField(blank=True, to='option.Option'),
        ),
        migrations.AddField(
            model_name='amquestion',
            name='shGroup',
            field=models.ManyToManyField(blank=True, to='shgroup.SHGroup'),
        ),
        migrations.AddField(
            model_name='amquestion',
            name='skipOption',
            field=models.ManyToManyField(blank=True, to='option.SkipOption'),
        ),
        migrations.AddField(
            model_name='amquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AddIndex(
            model_name='amresponse',
            index=models.Index(fields=['created_at'], name='aboutme_amr_created_eaa68a_idx'),
        ),
    ]
