# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-09 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page_setting', '0001_initial'),
        ('aboutme', '0001_initial'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pageamquestion',
            name='pageSetting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ampagesetting', to='page_setting.PageSetting'),
        ),
        migrations.AddField(
            model_name='amresponsetopic',
            name='amResponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutme.AMResponse'),
        ),
        migrations.AddField(
            model_name='amresponse',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutme.AMQuestion'),
        ),
        migrations.AddField(
            model_name='amresponse',
            name='subjectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amSubjectUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='amresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amquestionshgroup',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutme.AMQuestion'),
        ),
    ]
