# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-03-16 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_auto_20220302_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='amresponseacknowledgement',
            name='ackEmailSent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amresponseacknowledgement',
            name='flagEmailSent',
            field=models.BooleanField(default=False),
        ),
    ]
