# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-16 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0005_amresponse_controltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amresponse',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutme.AMQuestion', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='amresponse',
            name='commentValue',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='amresponse',
            name='integerValue',
            field=models.PositiveIntegerField(blank=True, verbose_name='Answer(Int)'),
        ),
        migrations.AlterField(
            model_name='amresponse',
            name='skipValue',
            field=models.TextField(blank=True, verbose_name='Answer(Skip)'),
        ),
        migrations.AlterField(
            model_name='amresponse',
            name='topicValue',
            field=models.TextField(blank=True, verbose_name='Answer(Text)'),
        ),
    ]
