# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-15 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0012_amquestion_amqorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amquestion',
            options={'ordering': ['amqOrder']},
        ),
    ]
