# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-15 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0013_auto_20200515_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amquestion',
            name='amqOrder',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
