# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-04 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0015_auto_20200521_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='amquestion',
            name='longForm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amquestion',
            name='shortForm',
            field=models.BooleanField(default=False),
        ),
    ]
