# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0016_auto_20200603_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='amquestion',
            name='isStandard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amquestion',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Driver'),
        ),
    ]
