# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0017_auto_20200617_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='amquestionoption',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMQuestion'),
        ),
        migrations.AlterField(
            model_name='amquestionoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option'),
        ),
        migrations.AlterField(
            model_name='amquestionshgroup',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMQuestion'),
        ),
        migrations.AlterField(
            model_name='amquestionshgroup',
            name='shGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shgroup.SHGroup'),
        ),
        migrations.AlterField(
            model_name='amquestionskipoption',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMQuestion'),
        ),
        migrations.AlterField(
            model_name='amquestionskipoption',
            name='skipOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.SkipOption'),
        ),
        migrations.AlterField(
            model_name='amresponse',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMQuestion', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='amresponse',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Project'),
        ),
        migrations.AlterField(
            model_name='amresponse',
            name='projectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amProjectUser', to='shgroup.ProjectUser'),
        ),
        migrations.AlterField(
            model_name='amresponse',
            name='subProjectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amSubProjectUser', to='shgroup.ProjectUser'),
        ),
        migrations.AlterField(
            model_name='amresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='amresponsetopic',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMQuestion'),
        ),
        migrations.AlterField(
            model_name='amresponsetopic',
            name='responseUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shgroup.ProjectUser'),
        ),
        migrations.AlterField(
            model_name='pageamquestion',
            name='amQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMQuestion'),
        ),
    ]
