# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-09-09 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0020_auto_20200827_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMResponseSentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(blank=True, max_length=30)),
                ('positiveValue', models.FloatField(blank=True)),
                ('neutralValue', models.FloatField(blank=True)),
                ('negativeValue', models.FloatField(blank=True)),
                ('mixedValue', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMResponse')),
            ],
        ),
    ]
