# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-01-14 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0022_amresponseacknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='amresponseacknowledgement',
            name='actionType',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='amresponseacknowledgement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amresponseacknowledgement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
