# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-02-23 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0023_auto_20210114_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amresponseacknowledgement',
            name='amResponse',
        ),
        migrations.RemoveField(
            model_name='amresponseacknowledgement',
            name='project',
        ),
        migrations.RemoveField(
            model_name='amresponseacknowledgement',
            name='survey',
        ),
        migrations.DeleteModel(
            name='AMResponseAcknowledgement',
        ),
    ]
