# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-03-09 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0030_projectuser_sendinvite'),
        ('aboutme', '0024_auto_20210223_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMResponseAcknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeStatus', models.PositiveIntegerField(default=0)),
                ('acknowledgeStatus', models.PositiveIntegerField(default=0)),
                ('flagStatus', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('AMResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.AMResponse')),
                ('projectUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amCommentProjectUser', to='shgroup.ProjectUser')),
            ],
        ),
    ]
