# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-03-10 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0025_amresponseacknowledgement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amresponseacknowledgement',
            old_name='AMResponse',
            new_name='amResponse',
        ),
    ]
