# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-04-02 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0027_amresponse_latestreponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amresponse',
            name='latestReponse',
        ),
        migrations.AddField(
            model_name='amresponse',
            name='latestResponse',
            field=models.BooleanField(default=True),
        ),
    ]
