# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-02-14 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0029_auto_20210629_1744'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='amresponse',
            index=models.Index(fields=['created_at'], name='aboutme_amr_created_eaa68a_idx'),
        ),
    ]
