# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-03-16 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0030_auto_20220214_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='amresponseacknowledgement',
            name='ackEmailSent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amresponseacknowledgement',
            name='flagEmailSent',
            field=models.BooleanField(default=False),
        ),
    ]
