# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-04-04 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0034_amresponseacknowledgement_orgamresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amresponseacknowledgement',
            name='orgAmResponse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_am_response', to='aboutme.AMResponse'),
        ),
    ]
