# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-05-15 13:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0035_auto_20220405_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='amresponsetopic',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
