# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '__first__'),
        ('shgroup', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page_setting', '__first__'),
        ('survey', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AOPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoPageName', models.CharField(max_length=50)),
                ('aoPageSequence', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AOQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdriver', models.CharField(blank=True, max_length=50)),
                ('questionText', models.CharField(max_length=1000)),
                ('questionSequence', models.PositiveIntegerField(default=5)),
                ('sliderTextLeft', models.CharField(blank=True, max_length=50)),
                ('sliderTextRight', models.CharField(blank=True, max_length=50)),
                ('skipOptionYN', models.BooleanField(default=True)),
                ('skipResponses', models.CharField(blank=True, max_length=1000)),
                ('topicPrompt', models.CharField(blank=True, max_length=255)),
                ('commentPrompt', models.CharField(blank=True, max_length=255)),
                ('PageSetting', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aopagesetting', to='page_setting.PageSetting')),
                ('controlType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.ControlType')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Driver')),
                ('shGroup', models.ManyToManyField(blank=True, to='shgroup.SHGroup')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='AOQuestionSHGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoQuestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOQuestion')),
                ('shGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shgroup.SHGroup')),
            ],
        ),
        migrations.CreateModel(
            name='AOResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integerValue', models.PositiveIntegerField(blank=True)),
                ('topicValue', models.TextField(blank=True)),
                ('commentValue', models.TextField(blank=True)),
                ('skipValue', models.TextField(blank=True)),
                ('topicTags', models.TextField(blank=True)),
                ('commentTags', models.TextField(blank=True)),
                ('aoQuestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOQuestion')),
                ('subjectUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aoSubjectUser', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aoUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AOResponseTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('aoResponse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOResponse')),
            ],
        ),
        migrations.CreateModel(
            name='PageAOQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoQuestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOQuestion')),
                ('pageSetting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='page_setting.PageSetting')),
            ],
        ),
    ]
