# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-03-02 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AOPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoPageName', models.CharField(max_length=50)),
                ('aoPageSequence', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AOQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdriver', models.CharField(blank=True, max_length=50)),
                ('questionText', models.CharField(max_length=1000)),
                ('questionSequence', models.PositiveIntegerField(default=5)),
                ('sliderTextLeft', models.CharField(blank=True, max_length=50)),
                ('sliderTextRight', models.CharField(blank=True, max_length=50)),
                ('skipOptionYN', models.BooleanField(default=True)),
                ('topicPrompt', models.CharField(blank=True, max_length=255)),
                ('commentPrompt', models.CharField(blank=True, max_length=255)),
                ('aoqOrder', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('shortForm', models.BooleanField(default=False)),
                ('longForm', models.BooleanField(default=False)),
                ('isStandard', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['aoqOrder'],
            },
        ),
        migrations.CreateModel(
            name='AOQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AOQuestionSHGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AOQuestionSkipOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AOResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlType', models.CharField(max_length=30)),
                ('integerValue', models.PositiveIntegerField(blank=True)),
                ('topicValue', models.TextField(blank=True)),
                ('commentValue', models.TextField(blank=True)),
                ('skipValue', models.TextField(blank=True)),
                ('topicTags', models.TextField(blank=True)),
                ('commentTags', models.TextField(blank=True)),
                ('latestResponse', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AOResponseAcknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeStatus', models.PositiveIntegerField(default=0)),
                ('acknowledgeStatus', models.PositiveIntegerField(default=0)),
                ('flagStatus', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AOResponseTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(blank=True, max_length=255)),
                ('topicComment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageAOQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOQuestion')),
            ],
        ),
    ]
