# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-09 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page_setting', '0001_initial'),
        ('option', '0001_initial'),
        ('aboutothers', '0001_initial'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pageaoquestion',
            name='pageSetting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aopagesetting', to='page_setting.PageSetting'),
        ),
        migrations.AddField(
            model_name='aoresponsetopic',
            name='aoResponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOResponse'),
        ),
        migrations.AddField(
            model_name='aoresponse',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOQuestion'),
        ),
        migrations.AddField(
            model_name='aoresponse',
            name='subjectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aoSubjectUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aoresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='aoresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aoUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aoquestionskipoption',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOQuestion'),
        ),
        migrations.AddField(
            model_name='aoquestionskipoption',
            name='skipOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='option.SkipOption'),
        ),
        migrations.AddField(
            model_name='aoquestionshgroup',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOQuestion'),
        ),
    ]
