# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aoquestion',
            name='PageSetting',
        ),
        migrations.AlterField(
            model_name='pageaoquestion',
            name='pageSetting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aopagesetting', to='page_setting.PageSetting'),
        ),
    ]
