# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-03-02 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
        ('shgroup', '0001_initial'),
        ('setting', '0001_initial'),
        ('option', '0001_initial'),
        ('aboutothers', '0001_initial'),
        ('page_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageaoquestion',
            name='pageSetting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aopagesetting', to='page_setting.PageSetting'),
        ),
        migrations.AddField(
            model_name='aoresponsetopic',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOQuestion'),
        ),
        migrations.AddField(
            model_name='aoresponsetopic',
            name='responseUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shgroup.ProjectUser'),
        ),
        migrations.AddField(
            model_name='aoresponseacknowledgement',
            name='aoResponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOResponse'),
        ),
        migrations.AddField(
            model_name='aoresponseacknowledgement',
            name='projectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aoCommentProjectUser', to='shgroup.ProjectUser'),
        ),
        migrations.AddField(
            model_name='aoresponse',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOQuestion'),
        ),
        migrations.AddField(
            model_name='aoresponse',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Project'),
        ),
        migrations.AddField(
            model_name='aoresponse',
            name='projectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aoProjectUser', to='shgroup.ProjectUser'),
        ),
        migrations.AddField(
            model_name='aoresponse',
            name='shCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shgroup.SHCategory'),
        ),
        migrations.AddField(
            model_name='aoresponse',
            name='subProjectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aoSubProjectUser', to='shgroup.ProjectUser'),
        ),
        migrations.AddField(
            model_name='aoresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='aoquestionskipoption',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOQuestion'),
        ),
        migrations.AddField(
            model_name='aoquestionskipoption',
            name='skipOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.SkipOption'),
        ),
        migrations.AddField(
            model_name='aoquestionshgroup',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOQuestion'),
        ),
        migrations.AddField(
            model_name='aoquestionshgroup',
            name='shGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shgroup.SHGroup'),
        ),
        migrations.AddField(
            model_name='aoquestionoption',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOQuestion'),
        ),
        migrations.AddField(
            model_name='aoquestionoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option'),
        ),
        migrations.AddField(
            model_name='aoquestion',
            name='controlType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.ControlType'),
        ),
        migrations.AddField(
            model_name='aoquestion',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Driver'),
        ),
        migrations.AddField(
            model_name='aoquestion',
            name='option',
            field=models.ManyToManyField(blank=True, to='option.Option'),
        ),
        migrations.AddField(
            model_name='aoquestion',
            name='shGroup',
            field=models.ManyToManyField(blank=True, to='shgroup.SHGroup'),
        ),
        migrations.AddField(
            model_name='aoquestion',
            name='skipOption',
            field=models.ManyToManyField(blank=True, to='option.SkipOption'),
        ),
        migrations.AddField(
            model_name='aoquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
    ]
