# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-09 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
        ('aboutothers', '0002_auto_20191101_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='AOQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='aoquestion',
            name='option',
            field=models.ManyToManyField(blank=True, to='option.Option'),
        ),
        migrations.AddField(
            model_name='aoquestionoption',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOQuestion'),
        ),
        migrations.AddField(
            model_name='aoquestionoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='option.Option'),
        ),
    ]
