# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-14 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_project_client'),
        ('aboutothers', '0003_auto_20200109_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoresponse',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='survey.Project'),
            preserve_default=False,
        ),
    ]
