# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0003_auto_20191019_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoquestion',
            name='controlType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.ControlType'),
        ),
        migrations.AlterField(
            model_name='aoquestion',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Driver'),
        ),
        migrations.AlterField(
            model_name='aoquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='aoquestionshgroup',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOQuestion'),
        ),
        migrations.AlterField(
            model_name='aoquestionshgroup',
            name='shGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shgroup.SHGroup'),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOQuestion'),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='subjectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aoSubjectUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aoUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aoresponsetopic',
            name='aoResponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOResponse'),
        ),
    ]
