# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0002_auto_20191029_2107'),
        ('aboutothers', '0004_auto_20191029_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoquestion',
            name='shGroup',
            field=models.ManyToManyField(blank=True, to='shgroup.SHGroup'),
        ),
    ]
