# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0005_aoquestion_shgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoquestion',
            name='commentPrompt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aoquestion',
            name='questionSequence',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='aoquestion',
            name='skipResponses',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='aoquestion',
            name='sliderTextLeft',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='aoquestion',
            name='sliderTextRight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='aoquestion',
            name='subdriver',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='aoquestion',
            name='topicPrompt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='commentTags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='commentValue',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='integerValue',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='skipValue',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='topicTags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='topicValue',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aoresponsetopic',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='aoresponsetopic',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
