# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-25 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0010_auto_20200318_0233'),
        ('aboutothers', '0005_aoresponse_controltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aoresponsetopic',
            name='aoResponse',
        ),
        migrations.RemoveField(
            model_name='aoresponsetopic',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='aoresponsetopic',
            name='topic',
        ),
        migrations.AddField(
            model_name='aoresponsetopic',
            name='AOQuestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOQuestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aoresponsetopic',
            name='responseUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shgroup.ProjectUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aoresponsetopic',
            name='topicName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
