# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_setting', '0007_auto_20191030_1139'),
        ('aboutothers', '0006_auto_20191030_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAOQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoQuestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aboutothers.AOQuestion')),
                ('pageSetting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='page_setting.PageSetting')),
            ],
        ),
    ]
