# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-25 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0006_auto_20200325_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aoresponsetopic',
            old_name='AOQuestion',
            new_name='aoQuestion',
        ),
    ]
