# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-26 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0007_auto_20200325_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoresponsetopic',
            name='topicComment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
