# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-31 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0008_aoresponsetopic_topiccomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoquestion',
            name='controlType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.ControlType'),
        ),
    ]
