# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-05 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0009_auto_20200331_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aoquestion',
            name='skipResponses',
        ),
    ]
