# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-21 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0019_auto_20200520_2015'),
        ('aboutothers', '0011_auto_20200515_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aoresponse',
            name='subjectUser',
        ),
        migrations.RemoveField(
            model_name='aoresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='aoresponse',
            name='projectUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aoProjectUser', to='shgroup.ProjectUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aoresponse',
            name='subProjectUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aoSubProjectUser', to='shgroup.ProjectUser'),
            preserve_default=False,
        ),
    ]
