# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-28 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0012_auto_20200521_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoresponse',
            name='subProjectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aoSubProjectUser', to='shgroup.SHMapping'),
        ),
    ]
