# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-04 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0015_auto_20200603_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoquestion',
            name='longForm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aoquestion',
            name='shortForm',
            field=models.BooleanField(default=False),
        ),
    ]
