# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-09 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0016_auto_20200603_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoresponse',
            name='subProjectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aoSubProjectUser', to='shgroup.ProjectUser'),
        ),
    ]
