# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0018_auto_20200617_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='aoquestionoption',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOQuestion'),
        ),
        migrations.AlterField(
            model_name='aoquestionoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.Option'),
        ),
        migrations.AlterField(
            model_name='aoquestionshgroup',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOQuestion'),
        ),
        migrations.AlterField(
            model_name='aoquestionshgroup',
            name='shGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shgroup.SHGroup'),
        ),
        migrations.AlterField(
            model_name='aoquestionskipoption',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOQuestion'),
        ),
        migrations.AlterField(
            model_name='aoquestionskipoption',
            name='skipOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.SkipOption'),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOQuestion'),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Project'),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='projectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aoProjectUser', to='shgroup.ProjectUser'),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='subProjectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aoSubProjectUser', to='shgroup.ProjectUser'),
        ),
        migrations.AlterField(
            model_name='aoresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='aoresponsetopic',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOQuestion'),
        ),
        migrations.AlterField(
            model_name='aoresponsetopic',
            name='responseUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shgroup.ProjectUser'),
        ),
        migrations.AlterField(
            model_name='pageaoquestion',
            name='aoQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutothers.AOQuestion'),
        ),
    ]
