# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-08-20 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0028_auto_20200617_1335'),
        ('aboutothers', '0019_auto_20200617_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoresponse',
            name='shCategory',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='shgroup.SHCategory'),
            preserve_default=False,
        ),
    ]
