# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-02-23 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutothers', '0024_aoresponseacknowledgement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aoresponseacknowledgement',
            name='aoResponse',
        ),
        migrations.RemoveField(
            model_name='aoresponseacknowledgement',
            name='project',
        ),
        migrations.RemoveField(
            model_name='aoresponseacknowledgement',
            name='survey',
        ),
        migrations.DeleteModel(
            name='AOResponseAcknowledgement',
        ),
    ]
